name: Get Secret


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  retrieve_secret:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Repository Secret
        env:
          MY_SECRET: ${{ secrets.TEST_SECRET_1 }}
        run: |
          echo "Using secret in workflow"
          # Example of using the secret (don't actually echo secrets in production!)
          # echo $MY_SECRET 
